#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Audio-OSC
version:      0.04
version_from: lib/Audio/OSC.pm
installdirs:  site
requires:
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
